apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: open-match
  name: open-match-frontend
spec:
  rules:
    - host: {{ .Values.frontend.host | quote }}
      http:
        paths:
          - path: /v1/frontendservice
            pathType: Prefix
            backend:
              service:
                name: open-match-frontend
                port:
                  number: 51504
